-- Expand additive product master with major reef supplement lineups.

INSERT INTO public.additive_products (brand, name, category, default_unit, source_url, sort_order)
VALUES
  ('Red Sea', 'Reef Foundation A Calcium+', 'Calcium / strontium', 'ml', 'https://g1.redseafish.com/reef-care-program/reef_foundation_program/', 100),
  ('Red Sea', 'Reef Foundation B KH/Alkalinity', 'Alkalinity', 'ml', 'https://g1.redseafish.com/reef-care-program/reef_foundation_program/', 101),
  ('Red Sea', 'Reef Foundation C Magnesium', 'Magnesium', 'ml', 'https://g1.redseafish.com/reef-care-program/reef_foundation_program/', 102),
  ('Red Sea', 'Reef Foundation ABC+', 'Ca/KH/Mg powder', 'g', 'https://g1.redseafish.com/reef-care-program/reef_foundation_program/', 103),
  ('Red Sea', 'Reef Energy Plus AB+', 'Coral nutrition', 'ml', 'https://g1.redseafish.com/reef-care-program/', 110),
  ('Red Sea', 'Trace Colors A Iodine+', 'Trace colors', 'ml', 'https://g1.redseafish.com/support/faq/products/trace-colors/', 120),
  ('Red Sea', 'Trace Colors B Potassium+', 'Trace colors', 'ml', 'https://g1.redseafish.com/support/faq/products/trace-colors/', 121),
  ('Red Sea', 'Trace Colors C Iron+', 'Trace colors', 'ml', 'https://g1.redseafish.com/support/faq/products/trace-colors/', 122),
  ('Red Sea', 'Trace Colors D Bioactive Elements', 'Trace colors', 'ml', 'https://g1.redseafish.com/support/faq/products/trace-colors/', 123),
  ('Red Sea', 'NO3:PO4-X', 'Nitrate / phosphate control', 'ml', 'https://g1.redseafish.com/reef-care-program/no3po4-x-old/', 130),
  ('Red Sea', 'KH Coralline Gro', 'Alkalinity / coralline algae', 'ml', 'https://g1.redseafish.com/reef-care-program/', 131),

  ('Fauna Marin', 'Ready2Reef', 'All-in-one Ca/KH/Mg/trace', 'ml', 'https://www.faunamarin.de/produkte/wasseraufbereitung/balling-light/', 200),
  ('Fauna Marin', 'Balling Light Calcium-Mix', 'Calcium balling salt', 'g', 'https://www.faunamarin.de/produkte/wasseraufbereitung/balling-light/', 201),
  ('Fauna Marin', 'Balling Light Magnesium-Mix', 'Magnesium balling salt', 'g', 'https://www.faunamarin.de/produkte/wasseraufbereitung/balling-light/', 202),
  ('Fauna Marin', 'Balling Light Carbonate-Mix', 'Alkalinity balling salt', 'g', 'https://www.faunamarin.de/produkte/wasseraufbereitung/balling-light/', 203),
  ('Fauna Marin', 'Balling Light Trace 1', 'Trace elements', 'ml', 'https://www.faunamarin.de/balling-light-trace-1/', 210),
  ('Fauna Marin', 'Balling Light Trace 2', 'Trace elements', 'ml', 'https://www.faunamarin.de/produkte/wasseraufbereitung/balling-light/', 211),
  ('Fauna Marin', 'Balling Light Trace 3', 'Trace elements', 'ml', 'https://www.faunamarin.de/produkte/wasseraufbereitung/balling-light/', 212),
  ('Fauna Marin', 'Elementals Ca', 'Calcium', 'ml', 'https://www.faunamarin.de/wp-content/uploads/2021/04/FM_HTU_ELEMENTALS_EINFUeHRUNG_EN_NEU_291121.pdf', 220),
  ('Fauna Marin', 'Elementals Mg', 'Magnesium', 'ml', 'https://www.faunamarin.de/wp-content/uploads/2021/04/FM_HTU_ELEMENTALS_EINFUeHRUNG_EN_NEU_291121.pdf', 221),
  ('Fauna Marin', 'Elementals KH', 'Alkalinity', 'ml', 'https://www.faunamarin.de/wp-content/uploads/2021/04/FM_HTU_ELEMENTALS_EINFUeHRUNG_EN_NEU_291121.pdf', 222),
  ('Fauna Marin', 'Elementals K', 'Potassium', 'ml', 'https://www.faunamarin.de/wp-content/uploads/2021/04/FM_HTU_ELEMENTALS_EINFUeHRUNG_EN_NEU_291121.pdf', 223),
  ('Fauna Marin', 'Elementals Sr', 'Strontium', 'ml', 'https://www.faunamarin.de/wp-content/uploads/2021/04/FM_HTU_ELEMENTALS_EINFUeHRUNG_EN_NEU_291121.pdf', 224),
  ('Fauna Marin', 'Elementals I', 'Iodine', 'ml', 'https://www.faunamarin.de/wp-content/uploads/2021/04/FM_HTU_ELEMENTALS_EINFUeHRUNG_EN_NEU_291121.pdf', 225),
  ('Fauna Marin', 'Elementals B', 'Boron', 'ml', 'https://www.faunamarin.de/wp-content/uploads/2021/04/FM_HTU_ELEMENTALS_EINFUeHRUNG_EN_NEU_291121.pdf', 226),
  ('Fauna Marin', 'Elementals Br', 'Bromine', 'ml', 'https://www.faunamarin.de/wp-content/uploads/2021/04/FM_HTU_ELEMENTALS_EINFUeHRUNG_EN_NEU_291121.pdf', 227),
  ('Fauna Marin', 'Elementals F', 'Fluorine', 'ml', 'https://www.faunamarin.de/wp-content/uploads/2021/04/FM_HTU_ELEMENTALS_EINFUeHRUNG_EN_NEU_291121.pdf', 228),
  ('Fauna Marin', 'Elementals Fe', 'Iron', 'ml', 'https://www.faunamarin.de/wp-content/uploads/2021/04/FM_HTU_ELEMENTALS_EINFUeHRUNG_EN_NEU_291121.pdf', 229),
  ('Fauna Marin', 'Elementals Zn', 'Zinc', 'ml', 'https://www.faunamarin.de/en/wissen-en/zinc/', 230),
  ('Fauna Marin', 'Elementals Mn', 'Manganese', 'ml', 'https://www.faunamarin.de/wp-content/uploads/2021/04/FM_HTU_ELEMENTALS_EINFUeHRUNG_EN_NEU_291121.pdf', 231),
  ('Fauna Marin', 'Elementals Mo', 'Molybdenum', 'ml', 'https://www.faunamarin.de/wp-content/uploads/2021/04/FM_HTU_ELEMENTALS_EINFUeHRUNG_EN_NEU_291121.pdf', 232),
  ('Fauna Marin', 'Elementals Ba', 'Barium', 'ml', 'https://www.faunamarin.de/wp-content/uploads/2021/04/FM_HTU_ELEMENTALS_EINFUeHRUNG_EN_NEU_291121.pdf', 233),
  ('Fauna Marin', 'Elementals Co', 'Cobalt', 'ml', 'https://www.faunamarin.de/en/knowledge-base/cobalt/', 234),
  ('Fauna Marin', 'Elementals Se', 'Selenium', 'ml', 'https://www.faunamarin.de/en/wissen-en/selenium/', 235),
  ('Fauna Marin', 'Organic', 'Organic trace / vitamins', 'ml', 'https://www.faunamarin.de/produkte/wasseraufbereitung/', 250),
  ('Fauna Marin', 'Min S', 'Coral food / amino', 'ml', 'https://www.faunamarin.de/en/knowledge-base/cobalt/', 251),
  ('Fauna Marin', 'Coral Sprint', 'Coral food', 'g', 'https://www.faunamarin.de/produkte/wasseraufbereitung/balling-light/', 252),
  ('Fauna Marin', 'Bacto Blend', 'Bacteria / nutrient control', 'ml', 'https://www.faunamarin.de/produkte/wasseraufbereitung/', 253),

  ('Seachem', 'Reef Fusion 1', 'Calcium', 'ml', 'https://www.seachem.com/reef-fusion.php', 300),
  ('Seachem', 'Reef Fusion 2', 'Alkalinity', 'ml', 'https://www.seachem.com/reef-fusion.php', 301),
  ('Seachem', 'Reef Complete', 'Calcium / magnesium / strontium', 'ml', 'https://www.seachem.com/reef-complete.php', 310),
  ('Seachem', 'Reef Calcium', 'Organic calcium', 'ml', 'https://www.seachem.com/reef-calcium.php', 311),
  ('Seachem', 'Reef Advantage Calcium', 'Calcium powder', 'g', 'https://www.seachem.com/reef-advantage-calcium.php', 312),
  ('Seachem', 'Reef Advantage Magnesium', 'Magnesium powder', 'g', 'https://www.seachem.com/reef-advantage-magnesium.php', 313),
  ('Seachem', 'Reef Builder', 'Alkalinity powder', 'g', 'https://www.seachem.com/reef-builder.php', 314),
  ('Seachem', 'Reef Buffer', 'pH / alkalinity powder', 'g', 'https://www.seachem.com/reef-buffer.php', 315),
  ('Seachem', 'Reef Carbonate', 'Alkalinity', 'ml', 'https://www.seachem.com/reef-carbonate.php', 316),
  ('Seachem', 'Reef Plus', 'Vitamins / amino acids', 'ml', 'https://www.seachem.com/reef-plus.php', 320),
  ('Seachem', 'Reef Trace', 'Trace elements', 'ml', 'https://www.seachem.com/reef-trace.php', 321),
  ('Seachem', 'Reef Iodide', 'Iodide', 'ml', 'https://www.seachem.com/reef-iodide.php', 322),
  ('Seachem', 'Reef Strontium', 'Strontium', 'ml', 'https://www.seachem.com/reef-strontium.php', 323),

  ('Aquaforest', 'Component 1+', 'Balling component', 'ml', 'https://aquaforest.eu/en/knowledge-base-tag/component-123/', 400),
  ('Aquaforest', 'Component 2+', 'Balling component', 'ml', 'https://aquaforest.eu/en/knowledge-base-tag/component-123/', 401),
  ('Aquaforest', 'Component 3+', 'Balling component', 'ml', 'https://aquaforest.eu/en/knowledge-base-tag/component-123/', 402),
  ('Aquaforest', 'Component 1 Pro', 'Balling component', 'ml', 'https://aquaforest.eu/en/products/lab/macroelements/components-pro/', 410),
  ('Aquaforest', 'Component 2 Pro', 'Balling component', 'ml', 'https://aquaforest.eu/en/products/lab/macroelements/components-pro/', 411),
  ('Aquaforest', 'Component 3 Pro', 'Balling component', 'ml', 'https://aquaforest.eu/en/products/lab/macroelements/components-pro/', 412),
  ('Aquaforest', 'Ca Plus', 'Calcium', 'ml', 'https://aquaforest.eu/wp-content/uploads/2024/09/AF_Products-Guide_EN_WEB_241120.pdf', 420),
  ('Aquaforest', 'Mg Plus', 'Magnesium', 'ml', 'https://aquaforest.eu/wp-content/uploads/2024/09/AF_Products-Guide_EN_WEB_241120.pdf', 421),
  ('Aquaforest', 'KH Plus', 'Alkalinity', 'ml', 'https://aquaforest.eu/en/products/seawater/water-treatment/kh-pro/', 422),
  ('Aquaforest', 'Component A', 'Trace elements', 'ml', 'https://aquaforest.eu/wp-content/uploads/2024/09/AF_Products-Guide_EN_WEB_241120.pdf', 430),
  ('Aquaforest', 'Component B', 'Trace elements', 'ml', 'https://aquaforest.eu/wp-content/uploads/2024/09/AF_Products-Guide_EN_WEB_241120.pdf', 431),
  ('Aquaforest', 'Component C', 'Trace elements', 'ml', 'https://aquaforest.eu/wp-content/uploads/2024/09/AF_Products-Guide_EN_WEB_241120.pdf', 432),
  ('Aquaforest', 'Component K', 'Trace elements', 'ml', 'https://aquaforest.eu/wp-content/uploads/2024/09/AF_Products-Guide_EN_WEB_241120.pdf', 433),
  ('Aquaforest', 'AF Build', 'Coral supplement', 'drop', 'https://aquaforest.eu/en/products/seawater/foods-and-supplementation/coral-fuel/', 440),
  ('Aquaforest', 'AF Energy', 'Coral nutrition', 'drop', 'https://aquaforest.eu/en/products/seawater/foods-and-supplementation/af-energy/', 441),
  ('Aquaforest', 'AF Vitality', 'Vitamins', 'drop', 'https://aquaforest.eu/en/products/seawater/foods-and-supplementation/coral-fuel/', 442),
  ('Aquaforest', 'AF Amino Mix', 'Amino acids', 'drop', 'https://aquaforest.eu/pl/produkty/seawater/foods-and-supplementation/af-amino-mix/', 443),
  ('Aquaforest', 'AF Power Elixir', 'Coral nutrition', 'ml', 'https://aquaforest.eu/wp-content/uploads/2025/03/Aquaforest_catalog_2025-WEB.pdf', 444),
  ('Aquaforest', 'Polyp Up', 'Polyp extension', 'drop', 'https://aquaforest.eu/en/products/seawater/foods-and-supplementation/coral-fuel/', 445),
  ('Aquaforest', 'AF Growth Boost', 'Coral growth supplement', 'g', 'https://aquaforest.eu/wp-content/uploads/2024/09/AF_Products-Guide_EN_WEB_241120.pdf', 446),
  ('Aquaforest', 'Pro Bio S', 'Probiotic bacteria', 'drop', 'https://aquaforest.eu/en/products/seawater/probiotic-method/np-pro/', 450),
  ('Aquaforest', '-NP Pro', 'Nitrate / phosphate control', 'ml', 'https://aquaforest.eu/en/products/seawater/probiotic-method/np-pro/', 451),
  ('Aquaforest', 'Life Source', 'Mineral mud', 'g', 'https://aquaforest.eu/wp-content/uploads/2024/09/AF_Products-Guide_EN_WEB_241120.pdf', 452),

  ('Tropic Marin', 'All-For-Reef', 'All-in-one Ca/KH/Mg/trace', 'ml', 'https://www.tropic-marin.com/meerwasser-produkte?lang=en', 500),
  ('Tropic Marin', 'All-For-Reef Powder', 'All-in-one Ca/KH/Mg/trace', 'g', 'https://www.tropic-marin.com/meerwasser-produkte?lang=en', 501),
  ('Tropic Marin', 'Carbo-Calcium', 'Calcium / alkalinity', 'ml', 'https://www.tropic-marin.com/meerwasser-produkte?lang=en', 510),
  ('Tropic Marin', 'Carbo-Calcium Powder', 'Calcium / alkalinity', 'g', 'https://www.tropic-marin.com/meerwasser-produkte?lang=en', 511),
  ('Tropic Marin', 'Original Balling Part A', 'Calcium balling solution', 'ml', 'https://www.tropic-marin.com/meerwasser-produkte?lang=en', 520),
  ('Tropic Marin', 'Original Balling Part B', 'Alkalinity balling solution', 'ml', 'https://www.tropic-marin.com/meerwasser-produkte?lang=en', 521),
  ('Tropic Marin', 'Balling Method Part C', 'Mineral salts', 'ml', 'https://www.tropic-marin.com/meerwasser-produkte?lang=en', 522),
  ('Tropic Marin', 'K+ Elements', 'Cationic trace elements', 'ml', 'https://www.tropic-marin.com/meerwasser-produkte?lang=en', 530),
  ('Tropic Marin', 'A- Elements', 'Anionic trace elements', 'ml', 'https://www.tropic-marin.com/meerwasser-produkte?lang=en', 531),
  ('Tropic Marin', 'Pro-Coral Mineral', 'Trace / minerals', 'ml', 'https://www.tropic-marin.com/meerwasser-produkte?lang=en', 532),
  ('Tropic Marin', 'Pro-Coral Iodine', 'Iodine', 'drop', 'https://www.tropic-marin.com/meerwasser-produkte?lang=en', 533),
  ('Tropic Marin', 'Bio-Calcium', 'Calcium / alkalinity powder', 'g', 'https://www.tropic-marin.com/meerwasser-produkte?lang=en', 540),
  ('Tropic Marin', 'Bio-Magnesium', 'Magnesium powder', 'g', 'https://www.tropic-marin.com/meerwasser-produkte?lang=en', 541),
  ('Tropic Marin', 'Elimi-NP', 'Nitrate / phosphate control', 'ml', 'https://www.tropic-marin.com/meerwasser-produkte?lang=en', 550),
  ('Tropic Marin', 'NP-Bacto-Balance', 'Nutrient control', 'ml', 'https://www.tropic-marin.com/meerwasser-produkte?lang=en', 551),
  ('Tropic Marin', 'Plus-NP', 'Nitrate / phosphate supplement', 'ml', 'https://www.tropic-marin.com/meerwasser-produkte?lang=en', 552),
  ('Tropic Marin', 'Phos-Feed', 'Phosphate supplement', 'ml', 'https://www.tropic-marin.com/meerwasser-produkte?lang=en', 553),
  ('Tropic Marin', 'Reef Actif', 'Organic biopolymer', 'g', 'https://www.tropic-marin.com/meerwasser-produkte?lang=en', 560),
  ('Tropic Marin', 'Amino-Organic', 'Amino acids', 'ml', 'https://www.tropic-marin.com/meerwasser-produkte?lang=en', 561),

  ('PolypLab', 'One', 'All-in-one Ca/KH/Mg', 'ml', 'https://www.polyplab.com/products/one', 600),
  ('PolypLab', 'Reef-Roids', 'Coral food', 'g', 'https://www.polyplab.com/products/reef-roids', 610),
  ('PolypLab', 'Polyp-Booster', 'Coral enhancer', 'ml', 'https://www.polyplab.com/products/polyp-booster', 611),
  ('PolypLab', 'Colors', 'Amino acids / color', 'drop', 'https://www.polyplab.com/products/colors', 612),
  ('PolypLab', 'System Reef-resh RF-Genesis', 'Bacteria', 'drop', 'https://www.polyplab.com/products/system-reef-resh', 620),
  ('PolypLab', 'System Reef-resh RF-Acids', 'Amino acids', 'drop', 'https://www.polyplab.com/products/system-reef-resh', 621),
  ('PolypLab', 'System Reef-resh RF-Plus', 'Coral nutrition', 'ml', 'https://www.polyplab.com/products/system-reef-resh', 622)
ON CONFLICT (brand, name) DO UPDATE SET
  category = EXCLUDED.category,
  default_unit = EXCLUDED.default_unit,
  source_url = EXCLUDED.source_url,
  sort_order = EXCLUDED.sort_order;
